[files.assets.config]
target_dir="src/warc2zim/statics"
execute_after=[
    "cd ../../../ && python rules/generate_rules.py", # generate Python and JS rules
    "cd ../../../javascript && yarn build-prod", # generate wombatSetup.js configuration
]

[files.assets.actions."wombat.js"]
action="get_file"
source="https://cdn.jsdelivr.net/npm/@webrecorder/wombat@3.7.0/dist/wombat.js"
target_file="wombat.js"
