name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[test,scripts]

      - name: Generate fuzzy rules
        run: python rules/generate_rules.py

      - name: Run the tests
        run: inv coverage --args "-vvv"

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Set up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JS dependencies
        working-directory: javascript
        run: yarn install

      - name: Run JS tests
        working-directory: javascript
        run: yarn test

  build_python:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip build
          pip install -e .[scripts]

      - name: Generate fuzzy rules
        run: python rules/generate_rules.py

      - name: Ensure we can build Python targets
        run: |
          pip install -U pip build
          python3 -m build --sdist --wheel

  build_docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Ensure we can build the Docker image
        run: |
          docker build -t testimage .

      - name: Ensure we can start the Docker image
        run: |
          docker run --rm testimage
